name: GitHub Action

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Github Actions
        run: echo Hello Github Actions!
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      # - name: Test
      #   run: npm run test
      - name: Build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run build
      - name: Step Summary
        run: echo "### Github Acitons done! :rocket:" >> $GITHUB_STEP_SUMMARY
